# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgregarSocio.ui'
#
# Created: Thu May 24 22:18:47 2018
#      by: PyQt5 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui


class Ui_Contacto(object):
    def setupUi(self, Contacto):
        Contacto.setObjectName("Contacto")
        Contacto.resize(352, 409)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(12)
        Contacto.setFont(font)
        Contacto.setCursor(QtCore.Qt.ArrowCursor)
        Contacto.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Bolivia))
        self.label_4 = QLabel(Contacto)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 311, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line = QFrame(Contacto)
        self.line.setGeometry(QtCore.QRect(10, 360, 331, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.lst_Socios = QListWidget(Contacto)
        self.lst_Socios.setGeometry(QtCore.QRect(10, 50, 141, 211))
        self.lst_Socios.setStyleSheet("\n"
"")
        self.lst_Socios.setObjectName("lst_Socios")
        self.line_2 = QFrame(Contacto)
        self.line_2.setGeometry(QtCore.QRect(10, 280, 331, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QWidget(Contacto)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 290, 331, 74))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QGridLayout(self.layoutWidget)
        # self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chkLockOperador = QCheckBox(self.layoutWidget)
        self.chkLockOperador.setObjectName("chkLockOperador")
        self.gridLayout_2.addWidget(self.chkLockOperador, 0, 0, 1, 1)
        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.chkLockReferidor = QCheckBox(self.layoutWidget)
        self.chkLockReferidor.setObjectName("chkLockReferidor")
        self.gridLayout_2.addWidget(self.chkLockReferidor, 1, 0, 1, 1)
        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.txtReferidor = QLineEdit(self.layoutWidget)
        self.txtReferidor.setEnabled(True)
        self.txtReferidor.setObjectName("txtReferidor")
        self.gridLayout_2.addWidget(self.txtReferidor, 1, 2, 1, 1)
        self.cboOperador = QComboBox(self.layoutWidget)
        self.cboOperador.setObjectName("cboOperador")
        self.gridLayout_2.addWidget(self.cboOperador, 0, 2, 1, 1)
        self.line_3 = QFrame(Contacto)
        self.line_3.setGeometry(QtCore.QRect(10, 30, 331, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.chkActivo = QCheckBox(Contacto)
        self.chkActivo.setGeometry(QtCore.QRect(160, 40, 181, 26))
        self.chkActivo.setChecked(True)
        self.chkActivo.setObjectName("chkActivo")
        self.layoutWidget1 = QWidget(Contacto)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 70, 181, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QGridLayout(self.layoutWidget1)
        # self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName("gridLayout")
        self.cboContacto1 = QComboBox(self.layoutWidget1)
        self.cboContacto1.setObjectName("cboContacto1")
        self.gridLayout.addWidget(self.cboContacto1, 0, 0, 1, 1)
        self.txtContacto1 = QLineEdit(self.layoutWidget1)
        self.txtContacto1.setObjectName("txtContacto1")
        self.gridLayout.addWidget(self.txtContacto1, 0, 1, 1, 1)
        self.label = QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.txtNombre = QLineEdit(self.layoutWidget1)
        self.txtNombre.setObjectName("txtNombre")
        self.gridLayout.addWidget(self.txtNombre, 1, 1, 1, 1)
        self.label_2 = QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.txtApellido = QLineEdit(self.layoutWidget1)
        self.txtApellido.setObjectName("txtApellido")
        self.gridLayout.addWidget(self.txtApellido, 2, 1, 1, 1)
        self.cboContacto2 = QComboBox(self.layoutWidget1)
        self.cboContacto2.setObjectName("cboContacto2")
        self.gridLayout.addWidget(self.cboContacto2, 3, 0, 1, 1)
        self.txtContacto2 = QLineEdit(self.layoutWidget1)
        self.txtContacto2.setObjectName("txtContacto2")
        self.gridLayout.addWidget(self.txtContacto2, 3, 1, 1, 1)
        self.label_5 = QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.cboRelacion = QComboBox(self.layoutWidget1)
        self.cboRelacion.setObjectName("cboRelacion")
        self.gridLayout.addWidget(self.cboRelacion, 4, 1, 1, 1)
        self.splitter = QSplitter(Contacto)
        self.splitter.setGeometry(QtCore.QRect(90, 370, 255, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btnLimpiar = QPushButton(self.splitter)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.btnGuardar = QPushButton(self.splitter)
        self.btnGuardar.setEnabled(False)
        self.btnGuardar.setObjectName("btnGuardar")
        self.btnSalir = QPushButton(self.splitter)
        self.btnSalir.setObjectName("btnSalir")
        self.lblFecha = QLabel(Contacto)
        self.lblFecha.setGeometry(QtCore.QRect(10, 260, 331, 21))
        self.lblFecha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFecha.setObjectName("lblFecha")
        self.label.setBuddy(self.txtContacto2)
        self.label_2.setBuddy(self.txtContacto1)

        self.retranslateUi(Contacto)
        QtCore.QMetaObject.connectSlotsByName(Contacto)
        Contacto.setTabOrder(self.chkActivo, self.txtContacto1)
        Contacto.setTabOrder(self.txtContacto1, self.txtNombre)
        Contacto.setTabOrder(self.txtNombre, self.txtApellido)
        Contacto.setTabOrder(self.txtApellido, self.cboRelacion)
        Contacto.setTabOrder(self.cboRelacion, self.chkLockOperador)
        Contacto.setTabOrder(self.chkLockOperador, self.chkLockReferidor)
        Contacto.setTabOrder(self.chkLockReferidor, self.txtReferidor)
        Contacto.setTabOrder(self.txtReferidor, self.btnGuardar)
        Contacto.setTabOrder(self.btnGuardar, self.btnLimpiar)
        Contacto.setTabOrder(self.btnLimpiar, self.cboContacto2)
        Contacto.setTabOrder(self.cboContacto2, self.txtContacto2)
        Contacto.setTabOrder(self.txtContacto2, self.cboContacto1)
        Contacto.setTabOrder(self.cboContacto1, self.lst_Socios)
        Contacto.setTabOrder(self.lst_Socios, self.btnSalir)

    def retranslateUi(self, Contacto):
        Contacto.setWindowTitle("Editar Contacto")
        self.label_4.setText("AGREGAR/EDITAR DATOS DEL SOCIO")
        self.chkLockOperador.setText("Retener")
        self.label_3.setText("Operador :")
        self.chkLockReferidor.setText("Retener")
        self.label_6.setText("Referido Por :")
        self.chkActivo.setText("Socio Activo del Club")
        self.label.setText("Nombre* :")
        self.label_2.setText("Apellido* :")
        self.label_5.setText("Relacion :")
        self.btnLimpiar.setText("Limpiar")
        self.btnGuardar.setText("Guardar")
        self.btnSalir.setText("Salir")
        self.lblFecha.setText("lblFecha")

