# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comanda_30dic16.ui'
#
# Created: Sun Jan  1 21:41:29 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(787, 621)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        Form.setFont(font)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 410, 181, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 10, 181, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 350, 181, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.tabMain = QtGui.QTabWidget(Form)
        self.tabMain.setGeometry(QtCore.QRect(200, 50, 581, 561))
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabAsistenciaGeneral = QtGui.QWidget()
        self.tabAsistenciaGeneral.setObjectName(_fromUtf8("tabAsistenciaGeneral"))
        self.tblAsistenciaGeneral = QtGui.QTableWidget(self.tabAsistenciaGeneral)
        self.tblAsistenciaGeneral.setGeometry(QtCore.QRect(10, 10, 421, 501))
        self.tblAsistenciaGeneral.setObjectName(_fromUtf8("tblAsistenciaGeneral"))
        self.tblAsistenciaGeneral.setColumnCount(0)
        self.tblAsistenciaGeneral.setRowCount(0)
        self.cboOperador = QtGui.QComboBox(self.tabAsistenciaGeneral)
        self.cboOperador.setGeometry(QtCore.QRect(442, 10, 121, 27))
        self.cboOperador.setObjectName(_fromUtf8("cboOperador"))
        self.layoutWidget_2 = QtGui.QWidget(self.tabAsistenciaGeneral)
        self.layoutWidget_2.setGeometry(QtCore.QRect(442, 40, 121, 126))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblConsumos = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblConsumos.setFont(font)
        self.lblConsumos.setObjectName(_fromUtf8("lblConsumos"))
        self.gridLayout_8.addWidget(self.lblConsumos, 0, 0, 1, 1)
        self.lblVentas = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblVentas.setFont(font)
        self.lblVentas.setObjectName(_fromUtf8("lblVentas"))
        self.gridLayout_8.addWidget(self.lblVentas, 1, 0, 1, 1)
        self.lblRojo = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblRojo.setFont(font)
        self.lblRojo.setObjectName(_fromUtf8("lblRojo"))
        self.gridLayout_8.addWidget(self.lblRojo, 2, 0, 1, 1)
        self.lblVerde = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblVerde.setFont(font)
        self.lblVerde.setObjectName(_fromUtf8("lblVerde"))
        self.gridLayout_8.addWidget(self.lblVerde, 3, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(self.tabAsistenciaGeneral)
        self.layoutWidget_3.setGeometry(QtCore.QRect(442, 180, 121, 111))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.efectivo = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.efectivo.setFont(font)
        self.efectivo.setObjectName(_fromUtf8("efectivo"))
        self.gridLayout_6.addWidget(self.efectivo, 0, 0, 1, 1)
        self.lblRojoReal = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblRojoReal.setFont(font)
        self.lblRojoReal.setObjectName(_fromUtf8("lblRojoReal"))
        self.gridLayout_6.addWidget(self.lblRojoReal, 1, 0, 1, 1)
        self.lblInsumos = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblInsumos.setFont(font)
        self.lblInsumos.setObjectName(_fromUtf8("lblInsumos"))
        self.gridLayout_6.addWidget(self.lblInsumos, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self.tabAsistenciaGeneral)
        self.line_5.setGeometry(QtCore.QRect(440, 170, 118, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.tabMain.addTab(self.tabAsistenciaGeneral, _fromUtf8(""))
        self.tabCotizador = QtGui.QWidget()
        self.tabCotizador.setObjectName(_fromUtf8("tabCotizador"))
        self.lblTotal_Productos = QtGui.QLabel(self.tabCotizador)
        self.lblTotal_Productos.setGeometry(QtCore.QRect(20, 430, 71, 71))
        self.lblTotal_Productos.setObjectName(_fromUtf8("lblTotal_Productos"))
        self.tabMain.addTab(self.tabCotizador, _fromUtf8(""))
        self.btnSalir = QtGui.QPushButton(Form)
        self.btnSalir.setGeometry(QtCore.QRect(660, 580, 101, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/Comanda/style5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon)
        self.btnSalir.setObjectName(_fromUtf8("btnSalir"))
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 321, 36))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblNombre = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.lblNombre.setFont(font)
        self.lblNombre.setObjectName(_fromUtf8("lblNombre"))
        self.gridLayout_2.addWidget(self.lblNombre, 0, 0, 1, 1)
        self.btnNombre = QtGui.QPushButton(self.layoutWidget1)
        self.btnNombre.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnNombre.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/Comanda/Add User Group Woman Man-48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNombre.setIcon(icon1)
        self.btnNombre.setObjectName(_fromUtf8("btnNombre"))
        self.gridLayout_2.addWidget(self.btnNombre, 0, 1, 1, 1)
        self.txtNombre = QtGui.QLineEdit(self.layoutWidget1)
        self.txtNombre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.txtNombre.setFont(font)
        self.txtNombre.setObjectName(_fromUtf8("txtNombre"))
        self.gridLayout_2.addWidget(self.txtNombre, 0, 2, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 420, 181, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.txtTotal = QtGui.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.txtTotal.setFont(font)
        self.txtTotal.setObjectName(_fromUtf8("txtTotal"))
        self.horizontalLayout_7.addWidget(self.txtTotal)
        self.btnLimpiar = QtGui.QPushButton(self.layoutWidget2)
        self.btnLimpiar.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/Comanda/gnome_edit_clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon2)
        self.btnLimpiar.setObjectName(_fromUtf8("btnLimpiar"))
        self.horizontalLayout_7.addWidget(self.btnLimpiar)
        self.btnGuardar = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.btnGuardar.setFont(font)
        self.btnGuardar.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/Comanda/media_floppy_green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGuardar.setIcon(icon3)
        self.btnGuardar.setObjectName(_fromUtf8("btnGuardar"))
        self.horizontalLayout_7.addWidget(self.btnGuardar)
        self.layoutWidget3 = QtGui.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 370, 181, 41))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chkPrePago = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.chkPrePago.setFont(font)
        self.chkPrePago.setChecked(False)
        self.chkPrePago.setObjectName(_fromUtf8("chkPrePago"))
        self.gridLayout_3.addWidget(self.chkPrePago, 0, 0, 1, 1)
        self.txtPrePago = QtGui.QLineEdit(self.layoutWidget3)
        self.txtPrePago.setEnabled(False)
        self.txtPrePago.setMaximumSize(QtCore.QSize(30, 30))
        self.txtPrePago.setBaseSize(QtCore.QSize(10, 10))
        self.txtPrePago.setInputMask(_fromUtf8(""))
        self.txtPrePago.setObjectName(_fromUtf8("txtPrePago"))
        self.gridLayout_3.addWidget(self.txtPrePago, 0, 1, 1, 1)
        self.cboPrePago = QtGui.QComboBox(self.layoutWidget3)
        self.cboPrePago.setEnabled(False)
        self.cboPrePago.setObjectName(_fromUtf8("cboPrePago"))
        self.gridLayout_3.addWidget(self.cboPrePago, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(11, 60, 51, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(60, 70, 131, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 90, 181, 260))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnFibra = QtGui.QPushButton(self.widget)
        self.btnFibra.setObjectName(_fromUtf8("btnFibra"))
        self.gridLayout.addWidget(self.btnFibra, 0, 0, 1, 1)
        self.lstExtras = QtGui.QListWidget(self.widget)
        self.lstExtras.setObjectName(_fromUtf8("lstExtras"))
        self.gridLayout.addWidget(self.lstExtras, 0, 1, 8, 1)
        self.btnProteina = QtGui.QPushButton(self.widget)
        self.btnProteina.setObjectName(_fromUtf8("btnProteina"))
        self.gridLayout.addWidget(self.btnProteina, 1, 0, 1, 1)
        self.btnAloe = QtGui.QPushButton(self.widget)
        self.btnAloe.setObjectName(_fromUtf8("btnAloe"))
        self.gridLayout.addWidget(self.btnAloe, 2, 0, 1, 1)
        self.btnTe = QtGui.QPushButton(self.widget)
        self.btnTe.setObjectName(_fromUtf8("btnTe"))
        self.gridLayout.addWidget(self.btnTe, 3, 0, 1, 1)
        self.btnBatido = QtGui.QPushButton(self.widget)
        self.btnBatido.setObjectName(_fromUtf8("btnBatido"))
        self.gridLayout.addWidget(self.btnBatido, 4, 0, 1, 1)
        self.btnLiftOff = QtGui.QPushButton(self.widget)
        self.btnLiftOff.setObjectName(_fromUtf8("btnLiftOff"))
        self.gridLayout.addWidget(self.btnLiftOff, 5, 0, 1, 1)
        self.btnRebuild = QtGui.QPushButton(self.widget)
        self.btnRebuild.setObjectName(_fromUtf8("btnRebuild"))
        self.gridLayout.addWidget(self.btnRebuild, 6, 0, 1, 1)
        self.btnHydrate = QtGui.QPushButton(self.widget)
        self.btnHydrate.setObjectName(_fromUtf8("btnHydrate"))
        self.gridLayout.addWidget(self.btnHydrate, 7, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_3.setText(_translate("Form", "Fecha:", None))
        self.label_5.setText(_translate("Form", "Consumos:", None))
        self.label_6.setText(_translate("Form", "Ventas :", None))
        self.label_9.setText(_translate("Form", "Rojo :", None))
        self.label.setText(_translate("Form", "Verde :", None))
        self.lblConsumos.setText(_translate("Form", "C", None))
        self.lblVentas.setText(_translate("Form", "TV", None))
        self.lblRojo.setText(_translate("Form", "SR", None))
        self.lblVerde.setText(_translate("Form", "SV", None))
        self.label_10.setText(_translate("Form", "Verde* :", None))
        self.label_8.setText(_translate("Form", "Rojo* :", None))
        self.label_7.setText(_translate("Form", "Insumos :", None))
        self.efectivo.setText(_translate("Form", "SVR", None))
        self.lblRojoReal.setText(_translate("Form", "SRR", None))
        self.lblInsumos.setText(_translate("Form", "IN", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAsistenciaGeneral), _translate("Form", "Asistencia General", None))
        self.lblTotal_Productos.setText(_translate("Form", "Cantidad: ", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabCotizador), _translate("Form", "Cotizador", None))
        self.btnSalir.setText(_translate("Form", "Salir", None))
        self.lblNombre.setText(_translate("Form", "Nombre:", None))
        self.label_4.setText(_translate("Form", "Total:", None))
        self.btnLimpiar.setToolTip(_translate("Form", "Limpiar", None))
        self.btnGuardar.setToolTip(_translate("Form", "Guardar", None))
        self.chkPrePago.setText(_translate("Form", "PrePago:", None))
        self.label_2.setText(_translate("Form", "Extra:", None))
        self.btnFibra.setText(_translate("Form", "Fibra", None))
        self.btnProteina.setText(_translate("Form", "Proteina", None))
        self.btnAloe.setText(_translate("Form", "Aloe", None))
        self.btnTe.setText(_translate("Form", "Te", None))
        self.btnBatido.setText(_translate("Form", "Batido", None))
        self.btnLiftOff.setText(_translate("Form", "LiftOff", None))
        self.btnRebuild.setText(_translate("Form", "Rebuild", None))
        self.btnHydrate.setText(_translate("Form", "Hydrate", None))

