# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyWindow2.ui'
#
# Created: Sat Apr 16 20:09:18 2016
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(599, 696)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tab_Main = QtGui.QTabWidget(self.centralwidget)
        self.tab_Main.setGeometry(QtCore.QRect(0, 110, 591, 531))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.tab_Main.setFont(font)
        self.tab_Main.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tab_Main.setTabPosition(QtGui.QTabWidget.West)
        self.tab_Main.setObjectName(_fromUtf8("tab_Main"))
        self.Registro = QtGui.QWidget()
        self.Registro.setObjectName(_fromUtf8("Registro"))
        self.tab_Registro = QtGui.QTabWidget(self.Registro)
        self.tab_Registro.setGeometry(QtCore.QRect(10, 50, 531, 471))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tab_Registro.setFont(font)
        self.tab_Registro.setMovable(True)
        self.tab_Registro.setObjectName(_fromUtf8("tab_Registro"))
        self.Asistencia = QtGui.QWidget()
        self.Asistencia.setObjectName(_fromUtf8("Asistencia"))
        self.tbl_Asistencia = QtGui.QTableWidget(self.Asistencia)
        self.tbl_Asistencia.setGeometry(QtCore.QRect(10, 10, 501, 421))
        self.tbl_Asistencia.setObjectName(_fromUtf8("tbl_Asistencia"))
        self.tbl_Asistencia.setColumnCount(0)
        self.tbl_Asistencia.setRowCount(0)
        self.tab_Registro.addTab(self.Asistencia, _fromUtf8(""))
        self.ProdCerrado = QtGui.QWidget()
        self.ProdCerrado.setObjectName(_fromUtf8("ProdCerrado"))
        self.tbl_prodCerrado = QtGui.QTableWidget(self.ProdCerrado)
        self.tbl_prodCerrado.setGeometry(QtCore.QRect(10, 10, 501, 171))
        self.tbl_prodCerrado.setObjectName(_fromUtf8("tbl_prodCerrado"))
        self.tbl_prodCerrado.setColumnCount(0)
        self.tbl_prodCerrado.setRowCount(0)
        self.lstProdEncontrado = QtGui.QListWidget(self.ProdCerrado)
        self.lstProdEncontrado.setGeometry(QtCore.QRect(10, 230, 501, 121))
        self.lstProdEncontrado.setObjectName(_fromUtf8("lstProdEncontrado"))
        self.splitter_3 = QtGui.QSplitter(self.ProdCerrado)
        self.splitter_3.setGeometry(QtCore.QRect(10, 190, 501, 29))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.cboCriterioBusqueda = QtGui.QComboBox(self.splitter_3)
        self.cboCriterioBusqueda.setEditable(True)
        self.cboCriterioBusqueda.setObjectName(_fromUtf8("cboCriterioBusqueda"))
        self.txtDescripcion = QtGui.QLineEdit(self.splitter_3)
        self.txtDescripcion.setObjectName(_fromUtf8("txtDescripcion"))
        self.tab_Registro.addTab(self.ProdCerrado, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 50, 251, 196))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.txt_AddName = QtGui.QLineEdit(self.layoutWidget_3)
        self.txt_AddName.setObjectName(_fromUtf8("txt_AddName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_AddName)
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.txt_AddLName = QtGui.QLineEdit(self.layoutWidget_3)
        self.txt_AddLName.setObjectName(_fromUtf8("txt_AddLName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_AddLName)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txt_AddCel1 = QtGui.QLineEdit(self.layoutWidget_3)
        self.txt_AddCel1.setObjectName(_fromUtf8("txt_AddCel1"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txt_AddCel1)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.txt_AddCel2 = QtGui.QLineEdit(self.layoutWidget_3)
        self.txt_AddCel2.setObjectName(_fromUtf8("txt_AddCel2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txt_AddCel2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_Limpiar = QtGui.QPushButton(self.layoutWidget_3)
        self.btn_Limpiar.setObjectName(_fromUtf8("btn_Limpiar"))
        self.gridLayout.addWidget(self.btn_Limpiar, 0, 0, 1, 1)
        self.btn_Guardar = QtGui.QPushButton(self.layoutWidget_3)
        self.btn_Guardar.setEnabled(False)
        self.btn_Guardar.setObjectName(_fromUtf8("btn_Guardar"))
        self.gridLayout.addWidget(self.btn_Guardar, 0, 1, 1, 1)
        self.formLayout.setLayout(4, QtGui.QFormLayout.SpanningRole, self.gridLayout)
        self.tab_Registro.addTab(self.tab, _fromUtf8(""))
        self.Mensajes = QtGui.QWidget()
        self.Mensajes.setObjectName(_fromUtf8("Mensajes"))
        self.tableWidget = QtGui.QTableWidget(self.Mensajes)
        self.tableWidget.setGeometry(QtCore.QRect(10, 280, 501, 101))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget = QtGui.QWidget(self.Mensajes)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 161, 151))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_7.addWidget(self.plainTextEdit)
        self.btnSMS = QtGui.QPushButton(self.layoutWidget)
        self.btnSMS.setObjectName(_fromUtf8("btnSMS"))
        self.verticalLayout_7.addWidget(self.btnSMS)
        self.layoutWidget_2 = QtGui.QWidget(self.Mensajes)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 14, 161, 105))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lblNombreCompleto = QtGui.QLabel(self.layoutWidget_2)
        self.lblNombreCompleto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNombreCompleto.setObjectName(_fromUtf8("lblNombreCompleto"))
        self.verticalLayout_6.addWidget(self.lblNombreCompleto)
        self.scrollPhonesArea = QtGui.QScrollArea(self.layoutWidget_2)
        self.scrollPhonesArea.setWidgetResizable(True)
        self.scrollPhonesArea.setObjectName(_fromUtf8("scrollPhonesArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 157, 76))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollPhonesArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollPhonesArea)
        self.tab_Registro.addTab(self.Mensajes, _fromUtf8(""))
        self.widget = QtGui.QWidget(self.Registro)
        self.widget.setGeometry(QtCore.QRect(12, 10, 311, 36))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btn_Agregar = QtGui.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Agregar.setFont(font)
        self.btn_Agregar.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("interface_negro.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Agregar.setIcon(icon)
        self.btn_Agregar.setIconSize(QtCore.QSize(24, 24))
        self.btn_Agregar.setObjectName(_fromUtf8("btn_Agregar"))
        self.gridLayout_3.addWidget(self.btn_Agregar, 0, 1, 1, 1)
        self.txt_Nombre = QtGui.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.txt_Nombre.setFont(font)
        self.txt_Nombre.setObjectName(_fromUtf8("txt_Nombre"))
        self.gridLayout_3.addWidget(self.txt_Nombre, 0, 2, 1, 1)
        self.lbl_Resultado = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        self.lbl_Resultado.setFont(font)
        self.lbl_Resultado.setObjectName(_fromUtf8("lbl_Resultado"))
        self.gridLayout_3.addWidget(self.lbl_Resultado, 0, 0, 1, 1)
        self.tab_Main.addTab(self.Registro, _fromUtf8(""))
        self.Reportes = QtGui.QWidget()
        self.Reportes.setObjectName(_fromUtf8("Reportes"))
        self.tab_Reportes = QtGui.QTabWidget(self.Reportes)
        self.tab_Reportes.setGeometry(QtCore.QRect(10, 10, 541, 511))
        self.tab_Reportes.setObjectName(_fromUtf8("tab_Reportes"))
        self.Mensual = QtGui.QWidget()
        self.Mensual.setObjectName(_fromUtf8("Mensual"))
        self.tbl_Rep_Mensual = QtGui.QTableWidget(self.Mensual)
        self.tbl_Rep_Mensual.setGeometry(QtCore.QRect(10, 10, 511, 461))
        self.tbl_Rep_Mensual.setObjectName(_fromUtf8("tbl_Rep_Mensual"))
        self.tbl_Rep_Mensual.setColumnCount(0)
        self.tbl_Rep_Mensual.setRowCount(0)
        self.tab_Reportes.addTab(self.Mensual, _fromUtf8(""))
        self.Semanal = QtGui.QWidget()
        self.Semanal.setObjectName(_fromUtf8("Semanal"))
        self.tbl_Rep_Semanal = QtGui.QTableWidget(self.Semanal)
        self.tbl_Rep_Semanal.setGeometry(QtCore.QRect(10, 280, 461, 71))
        self.tbl_Rep_Semanal.setObjectName(_fromUtf8("tbl_Rep_Semanal"))
        self.tbl_Rep_Semanal.setColumnCount(0)
        self.tbl_Rep_Semanal.setRowCount(0)
        self.lbl_Ganancia = QtGui.QLabel(self.Semanal)
        self.lbl_Ganancia.setGeometry(QtCore.QRect(20, 240, 121, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(16)
        self.lbl_Ganancia.setFont(font)
        self.lbl_Ganancia.setObjectName(_fromUtf8("lbl_Ganancia"))
        self.treeEncontrado = QtGui.QTreeWidget(self.Semanal)
        self.treeEncontrado.setGeometry(QtCore.QRect(340, 80, 169, 81))
        self.treeEncontrado.setObjectName(_fromUtf8("treeEncontrado"))
        self.treeEncontrado.headerItem().setText(0, _fromUtf8("1"))
        self.tvlRegistroAsistencia = QtGui.QTableView(self.Semanal)
        self.tvlRegistroAsistencia.setGeometry(QtCore.QRect(20, 20, 251, 192))
        self.tvlRegistroAsistencia.setObjectName(_fromUtf8("tvlRegistroAsistencia"))
        self.cboEncontrado = QtGui.QComboBox(self.Semanal)
        self.cboEncontrado.setGeometry(QtCore.QRect(380, 190, 65, 27))
        self.cboEncontrado.setObjectName(_fromUtf8("cboEncontrado"))
        self.tab_Reportes.addTab(self.Semanal, _fromUtf8(""))
        self.tab_Main.addTab(self.Reportes, _fromUtf8(""))
        self.layoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(190, 10, 401, 94))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.lbl_Rojo = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(28)
        self.lbl_Rojo.setFont(font)
        self.lbl_Rojo.setToolTip(_fromUtf8(""))
        self.lbl_Rojo.setFrameShape(QtGui.QFrame.Box)
        self.lbl_Rojo.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_Rojo.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_Rojo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lbl_Rojo.setMargin(0)
        self.lbl_Rojo.setIndent(-1)
        self.lbl_Rojo.setObjectName(_fromUtf8("lbl_Rojo"))
        self.gridLayout_2.addWidget(self.lbl_Rojo, 1, 0, 1, 1)
        self.lbl_Verde = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(28)
        self.lbl_Verde.setFont(font)
        self.lbl_Verde.setFrameShape(QtGui.QFrame.Box)
        self.lbl_Verde.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_Verde.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_Verde.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lbl_Verde.setMargin(0)
        self.lbl_Verde.setIndent(-1)
        self.lbl_Verde.setObjectName(_fromUtf8("lbl_Verde"))
        self.gridLayout_2.addWidget(self.lbl_Verde, 1, 1, 1, 1)
        self.lbl_Total = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(28)
        self.lbl_Total.setFont(font)
        self.lbl_Total.setFrameShape(QtGui.QFrame.Box)
        self.lbl_Total.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_Total.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_Total.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lbl_Total.setMargin(0)
        self.lbl_Total.setIndent(-1)
        self.lbl_Total.setObjectName(_fromUtf8("lbl_Total"))
        self.gridLayout_2.addWidget(self.lbl_Total, 1, 2, 1, 1)
        self.lbl_Consumos = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(28)
        self.lbl_Consumos.setFont(font)
        self.lbl_Consumos.setFrameShape(QtGui.QFrame.Box)
        self.lbl_Consumos.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_Consumos.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_Consumos.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lbl_Consumos.setMargin(0)
        self.lbl_Consumos.setIndent(-1)
        self.lbl_Consumos.setObjectName(_fromUtf8("lbl_Consumos"))
        self.gridLayout_2.addWidget(self.lbl_Consumos, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.mnuArchivo = QtGui.QMenu(self.menubar)
        self.mnuArchivo.setObjectName(_fromUtf8("mnuArchivo"))
        self.mnu_Editar = QtGui.QMenu(self.menubar)
        self.mnu_Editar.setObjectName(_fromUtf8("mnu_Editar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.sub_m_Salir = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.sub_m_Salir.setFont(font)
        self.sub_m_Salir.setObjectName(_fromUtf8("sub_m_Salir"))
        self.sub_m_Preferencias = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        self.sub_m_Preferencias.setFont(font)
        self.sub_m_Preferencias.setObjectName(_fromUtf8("sub_m_Preferencias"))
        self.mnuArchivo.addAction(self.sub_m_Salir)
        self.mnu_Editar.addAction(self.sub_m_Preferencias)
        self.menubar.addAction(self.mnuArchivo.menuAction())
        self.menubar.addAction(self.mnu_Editar.menuAction())
        self.label.setBuddy(self.txt_AddCel2)
        self.label_7.setBuddy(self.txt_AddCel1)
        self.label_8.setBuddy(self.txt_AddName)
        self.lbl_Resultado.setBuddy(self.txt_Nombre)

        self.retranslateUi(MainWindow)
        self.tab_Main.setCurrentIndex(0)
        self.tab_Registro.setCurrentIndex(0)
        self.cboCriterioBusqueda.setCurrentIndex(-1)
        self.tab_Reportes.setCurrentIndex(0)
        self.cboEncontrado.setCurrentIndex(-1)
        QtCore.QObject.connect(self.sub_m_Salir, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Engargolado", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Registro.setTabText(self.tab_Registro.indexOf(self.Asistencia), QtGui.QApplication.translate("MainWindow", "Asistencia", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Registro.setTabText(self.tab_Registro.indexOf(self.ProdCerrado), QtGui.QApplication.translate("MainWindow", "Producto Cerrado", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Nombre* :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Apellido* :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Cel 1 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Cel 2 :", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Limpiar.setText(QtGui.QApplication.translate("MainWindow", "Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Guardar.setText(QtGui.QApplication.translate("MainWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Registro.setTabText(self.tab_Registro.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Socios", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSMS.setText(QtGui.QApplication.translate("MainWindow", "Enviar Mensaje", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombreCompleto.setText(QtGui.QApplication.translate("MainWindow", "lblNombreCompleto", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Registro.setTabText(self.tab_Registro.indexOf(self.Mensajes), QtGui.QApplication.translate("MainWindow", "Mensajes", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Resultado.setText(QtGui.QApplication.translate("MainWindow", "Buscar :", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.Registro), QtGui.QApplication.translate("MainWindow", "Registro", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Reportes.setTabText(self.tab_Reportes.indexOf(self.Mensual), QtGui.QApplication.translate("MainWindow", "Mensual", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Ganancia.setText(QtGui.QApplication.translate("MainWindow", "Promedios", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Reportes.setTabText(self.tab_Reportes.indexOf(self.Semanal), QtGui.QApplication.translate("MainWindow", "Semanal", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.Reportes), QtGui.QApplication.translate("MainWindow", "Reportes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">ROJO:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00aa00;\">VERDE:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "TOTAL VENTAS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "CONSUMOS:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Rojo.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Verde.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Total.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Consumos.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "&Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.mnu_Editar.setTitle(QtGui.QApplication.translate("MainWindow", "&Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.sub_m_Salir.setText(QtGui.QApplication.translate("MainWindow", "&Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.sub_m_Preferencias.setText(QtGui.QApplication.translate("MainWindow", "Preferencias", None, QtGui.QApplication.UnicodeUTF8))

