# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporte.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(758, 669)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(12)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.btnSalir = QtWidgets.QPushButton(Form)
        self.btnSalir.setGeometry(QtCore.QRect(650, 630, 96, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.btnSalir.setFont(font)
        self.btnSalir.setObjectName("btnSalir")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 610, 741, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabMain = QtWidgets.QTabWidget(Form)
        self.tabMain.setGeometry(QtCore.QRect(10, 50, 631, 551))
        self.tabMain.setObjectName("tabMain")
        self.tabDiaria = QtWidgets.QWidget()
        self.tabDiaria.setObjectName("tabDiaria")
        self.tblDiaria = QtWidgets.QTableWidget(self.tabDiaria)
        self.tblDiaria.setEnabled(True)
        self.tblDiaria.setGeometry(QtCore.QRect(10, 10, 611, 501))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.tblDiaria.setFont(font)
        self.tblDiaria.setObjectName("tblDiaria")
        self.tblDiaria.setColumnCount(0)
        self.tblDiaria.setRowCount(0)
        self.tabMain.addTab(self.tabDiaria, "")
        self.tabSemanal = QtWidgets.QWidget()
        self.tabSemanal.setObjectName("tabSemanal")
        self.tblSemanal = QtWidgets.QTableWidget(self.tabSemanal)
        self.tblSemanal.setEnabled(False)
        self.tblSemanal.setGeometry(QtCore.QRect(10, 10, 611, 501))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.tblSemanal.setFont(font)
        self.tblSemanal.setObjectName("tblSemanal")
        self.tblSemanal.setColumnCount(0)
        self.tblSemanal.setRowCount(0)
        self.tabMain.addTab(self.tabSemanal, "")
        self.tabMensual = QtWidgets.QWidget()
        self.tabMensual.setObjectName("tabMensual")
        self.tblMensual = QtWidgets.QTableWidget(self.tabMensual)
        self.tblMensual.setEnabled(True)
        self.tblMensual.setGeometry(QtCore.QRect(10, 10, 611, 501))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.tblMensual.setFont(font)
        self.tblMensual.setObjectName("tblMensual")
        self.tblMensual.setColumnCount(0)
        self.tblMensual.setRowCount(0)
        self.tabMain.addTab(self.tabMensual, "")
        self.lblMensaje = QtWidgets.QLabel(Form)
        self.lblMensaje.setGeometry(QtCore.QRect(10, 630, 401, 31))
        self.lblMensaje.setObjectName("lblMensaje")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 12, 221, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.LayOutFecha = QtWidgets.QFormLayout(self.layoutWidget)
        self.LayOutFecha.setContentsMargins(0, 0, 0, 0)
        self.LayOutFecha.setObjectName("LayOutFecha")
        self.lblFecha = QtWidgets.QLabel(self.layoutWidget)
        self.lblFecha.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblFecha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFecha.setObjectName("lblFecha")
        self.LayOutFecha.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblFecha)
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setGeometry(QtCore.QRect(650, 80, 101, 251))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter = QtWidgets.QSplitter(self.splitter_4)
        self.splitter.setFrameShape(QtWidgets.QFrame.Box)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblConsumos = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblConsumos.setFont(font)
        self.lblConsumos.setTextFormat(QtCore.Qt.AutoText)
        self.lblConsumos.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConsumos.setObjectName("lblConsumos")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setFrameShape(QtWidgets.QFrame.Box)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lblSobreRojo = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblSobreRojo.setFont(font)
        self.lblSobreRojo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSobreRojo.setObjectName("lblSobreRojo")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setFrameShape(QtWidgets.QFrame.Box)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lblSobreVerde = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblSobreVerde.setFont(font)
        self.lblSobreVerde.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSobreVerde.setObjectName("lblSobreVerde")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(650, 460, 101, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.splitter_5 = QtWidgets.QSplitter(Form)
        self.splitter_5.setGeometry(QtCore.QRect(651, 480, 101, 81))
        self.splitter_5.setFrameShape(QtWidgets.QFrame.Box)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.label_5 = QtWidgets.QLabel(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lblSobreRojoReal = QtWidgets.QLabel(self.splitter_5)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblSobreRojoReal.setFont(font)
        self.lblSobreRojoReal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSobreRojoReal.setObjectName("lblSobreRojoReal")
        self.btnPrint = QtWidgets.QPushButton(Form)
        self.btnPrint.setGeometry(QtCore.QRect(650, 570, 98, 27))
        self.btnPrint.setObjectName("btnPrint")
        self.splitter_6 = QtWidgets.QSplitter(Form)
        self.splitter_6.setGeometry(QtCore.QRect(650, 340, 101, 81))
        self.splitter_6.setFrameShape(QtWidgets.QFrame.Box)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.label_6 = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lblTotalVendido = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblTotalVendido.setFont(font)
        self.lblTotalVendido.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalVendido.setObjectName("lblTotalVendido")
        self.splitter_7 = QtWidgets.QSplitter(Form)
        self.splitter_7.setGeometry(QtCore.QRect(471, 11, 281, 31))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.lblOperador = QtWidgets.QLabel(self.splitter_7)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.lblOperador.setFont(font)
        self.lblOperador.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOperador.setObjectName("lblOperador")
        self.cboOperador = QtWidgets.QComboBox(self.splitter_7)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        self.cboOperador.setFont(font)
        self.cboOperador.setObjectName("cboOperador")

        self.retranslateUi(Form)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnSalir.setText(_translate("Form", "&Salir"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabDiaria), _translate("Form", "Actividad Diaria"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabSemanal), _translate("Form", "Semanal"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabMensual), _translate("Form", "Mensual"))
        self.lblMensaje.setText(_translate("Form", "lblMensaje"))
        self.lblFecha.setText(_translate("Form", "Fecha:"))
        self.label.setText(_translate("Form", "Consumos"))
        self.lblConsumos.setText(_translate("Form", "#"))
        self.label_2.setText(_translate("Form", "Sobre Rojo"))
        self.lblSobreRojo.setText(_translate("Form", "#"))
        self.label_3.setText(_translate("Form", "Sobre Verde"))
        self.lblSobreVerde.setText(_translate("Form", "#"))
        self.label_5.setText(_translate("Form", " Sobre Rojo Real"))
        self.lblSobreRojoReal.setText(_translate("Form", "#"))
        self.btnPrint.setText(_translate("Form", "Im&primir"))
        self.label_6.setText(_translate("Form", "Total Vendido"))
        self.lblTotalVendido.setText(_translate("Form", "#"))
        self.lblOperador.setText(_translate("Form", "Operador:"))

